services:
  db:
    container_name: postgres
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
#       - postgres:/data/postgres
        - ./data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

#volumes:
#    postgres:
